// <auto-generated />
namespace Condominio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v101));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300057355_v1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
